### ISSUE TITLE
Consider moving `alanbernstein/pilosa-notebooks` to the pilosa/ org

### ISSUE THREAD

**Issue by travisturner** [pilosa/pdk#24]
The README.md file references `https://github.com/alanbernstein/pilosa-notebooks/blob/master/taxi-use-case.ipynb`

We should probably move this repo to the pilosa org so we aren't referencing alan's personal account.

**Comment by alanbernstein** [comment]
I have no problem with that, I'll do it now if there's no argument against. I can also transfer https://github.com/alanbernstein/pilosa-figures/.
