### ISSUE TITLE
holder.go / multiple-value uuid.NewV4() in single-value context

### ISSUE THREAD

**Issue by sahuguet** [pilosa/pdk#36]
Here is the error message when I do `go get github.com/pilosa/pdk`.
I am running `go version go1.9.1 darwin/amd64`.

`../pilosa/holder.go:443:18: multiple-value uuid.NewV4() in single-value context`

**Comment by jaffee** [comment]
@sahuguet try navigating to the PDK repo in your GOPATH and executing `make install`

This will take care of fetching the correct versions of all dependencies.

**Comment by sahuguet** [comment]
Actually, the culprit was PATH.
I had to add
`export PATH=$PATH:$GOPATH/bin` to make things work.

Thanks for the quick response.

**Comment by jaffee** [comment]
Thanks for your issue! I'll add a note to the README about adding GOPATH/bin to PATH
